const dislikes = [
  "messy people",
  "violence",
  "guns",
  "drugs",
  "spoiled brats",
  "cat people",
  "snarky clerks",
  "darkness",
  "horror",
  "spiders",
  "mazes",
  "men",
  "women",
  "outdoors",
  "his girlfriend",
  "men's rights activists (MRA)",
  "Jock Jiggety",
  "Racism",
  "Donald Trump",
  "insects",
  "bats",
  "lying people",
  "negativity",
  "liars",
  "jerks",
  "lazy guys",
  "crime",
  "vegetables",
  "cleaning",
  "sports",
  "cigarettes",
  "meat",
  "none",
  "KJ",
  "Dawn",
  "bullies",
  "people making fun of her weight",
  "white people (except close ones)",
  "rats",
  "people without cybertikana",
  "soy milk.",
  "loud places",
  "having a routine",
  "spicy food",
  "people thinking they can replace heavy equipment",
  "Nick failing everything",
  "cats",
  "writing a job description to a CV",
  "repeating it",
  "pus",
  "severe bacterial resistance",
  "competitive",
  "disloyal",
  "selfish",
  "rude",
  "crude",
  "abusive",
  "violent",
  "when people touch his flowers",
  "goths",
  "snobs",
  "hobos",
  "hobos",
  "their job",
  "fat people",
  "dainty ladies",
  "furries",
  "many",
  "most people",
  "tsunderes",
  "pride",
  "coffee",
  "tobacco",
  "Children",
  "laziness",
  "arrogant",
  "show-offs",
  "obnoxious",
  "insects (bugs)",
  "dishonest people",
  "mushroom (food)",
  "slow internet connection",
  "social events",
  "lazy people",
  "filthy people",
  "The military",
  "cops",
  "red clothes",
  "pears",
  "narrow-minded people",
  "pink",
  "poinsettias",
  "cold weather",
  "raw fish",
  "pickled meat",
  "peanuts",
  "stamps",
  "bazookas",
  "champagne",
  "beer",
  "avocado",
  "mushrooms",
  "ignorant people",
  "politics",
  "swine (animals)",
  "working",
  "peas",
  "dislikes swearing (it annoys them)",
  "he despises laziness",
  "Unfair laws",
  "vandalism",
  "cryptozoology",
  "cheating",
  "their fiance",
  "crumbs",
  "spills",
  "cows",
  "flying (insects and birds)",
  "movies that suck",
  "sharks",
  "talking on the telephone",
  "sharing videos or images that purport to show someone experiencing harm or suffering",
  "cheese",
  "dust",
  "mold",
  "storms",
  "the number four (phobia of gambling)",
  "druggies",
  "getting her hands dirty",
  "complex recipes",
  "bad fashion",
  "having no job",
  "finding someone else's job",
  "people with her job",
  "indecisive people",
  "smoking",
  "alcohol",
  "black-haired people",
  "not having her job",
  "indigo eyes",
  "children",
  "crowded spaces",
  "girly stuff",
  "salty food",
  "heights",
  "office",
  "school",
  "extreme fractions",
  "chaos",
  "dumb talk",
  "bitchiness",
  "sleep",
  "bad mouthing",
  "romance",
  "Tentacle",
  "goo",
  "tentacle goo",
  "bugs",
  "exercise",
  "dirt",
  "raisins",
  "ebenezer",
  "hurricanes",
  "snails",
  "Vladimir Surov",
  "slugs",
  "turtles",
  "blackheads",
  "crude jokes",
  "crowds",
  "prejudice",
  "job",
  "Lauda",
  "Wiccans",
  "disrespectful people",
  "backstabbers",
  "sinners",
  "crowded places",
  "ill-tempered people",
  "not meeting their expectations",
  "dogs",
  "moths",
  "long lines",
  "people who keep them waiting",
  "rudeness",
  "red onions",
  "television shows with bad grammar",
  "punctuality",
  "bugs (bugs)",
  "racism",
  "sexism",
  "pollution",
  "picky people",
  "rowdy customers",
  "pretty much everyone on the planet Earth",
  "creeps",
  "being alone",
  "messy",
  "untrustworthy",
  "egotistic people",
  "snob",
  "racist",
  "annoying people",
  "loud sounds",
  "waffle iron",
  "disorganized people",
  "pancake iron",
  "cheaters",
  "gold diggers",
  "love at first sight",
  "country music",
  "cliches",
  "mosquitoes",
  "birds",
  "nasty people",
  "messy stuff",
  "cat girls",
  "adult woman with high status",
  "wet stuff",
  "seagulls",
  "shellfish",
  "tropical plants",
  "kittens",
  "ants",
  "technology",
  "pork",
  "working with machines",
  "fish",
  "carbs",
  "water",
  "overly humid weather",
  "bad service",
];
const fears = [
  "Monkeys",
  "Normal",
  "Spiders",
  "Spears",
  "Globsters",
  "Krakens",
  "Sparrows",
  "Trees",
  "Strangler Figs",
  "The Bound One",
  "Siren",
  "Death Spheres",
  "Wild Boys",
  "Still Alive",
  "bugs",
  "loud noises",
  "crowds",
  "spiders",
  "Heights",
  "Failure",
  "birds",
  "Boredom",
  "Missing Out",
  "dust",
  "deep water",
  "dirt",
  "failing her exams",
  "dentists",
  "thunder",
  "fire",
  "clowns",
  "crowded places",
  "dogs",
  "Dogs",
  "butterflies",
  "Abandonment",
  "failing again",
  "Thunder",
  "airplanes",
  "enclosed spaces",
  "ending up jobless",
  "water",
  "getting pregnant",
  "having children",
  "dying alone",
  "wasp venom",
  "Roller coasters",
  "Sharks",
  "fish",
  "bugs",
  "Dirt",
  "germs",
  "being dirty",
  "Claustrophobia (fear of confined spaces)",
  "humiliation",
  "messing up the food at parties",
  "monkeys",
  "isolation",
  "snakes",
  "Moths",
  "cancer",
  "heights",
  "doctors",
  "public restrooms",
  "tooth decay",
  "Dust",
  "Reptiles",
  "Enclosed Spaces",
  "The Dark",
  "being needles",
  "diseases",
  "not able to sleep during snoring from partner",
  "slim",
  "being alone",
  "bullies",
  "closed spaces",
  "The world's core goes ice",
  "death of loved ones",
  "Arachnophobia (Spiders)",
  "social situation",
  "judgment",
  "Cripples",
  "maimed",
  "needy",
  "weakness",
  "insects",
  "leaving a mess",
  "misuse of resources",
  "Mice",
  "crowded spaces",
  "mice",
  "dead bodies",
  "high places",
  "hospitals",
  "my dad.",
  "Not at all",
  "loud sounds",
  "intimacy",
  "Dying alone",
  "rats",
  "claustrophobia",
  "short-sleeved people",
  "darkness",
  "deconstruction",
  "Inferiority",
  "car accident",
  "the dentist",
  "the police",
  "Cats",
  "eridolphobia (funnel spiders)",
  "nomophobia (being without a mobile phone",
  "computer",
  "or other device for extended periods)",
  "catoptrophobia (seeing one's reflection)",
  "coulrophobia (clowns)",
  "he fears being poisoned",
  "Oceans",
  "tattoos",
  "being stuck somewhere without anyone knowing",
  "childbirth",
  "open spaces",
  "failure",
  "Not being enough",
  "wild animals",
  "cockroaches",
  "the afterlife",
  "being late",
  "Rejection",
  "Ghosts",
  "Rats",
  "Failing",
  "clumsiness",
  "the dark",
  "tight spaces",
  "abandonment",
  "looking bad",
  "Slug slime",
  "Arachnophobia",
  "Claustrophobia",
  "public transportation",
  "sleeping alone",
  "sleeping",
  "The dark",
  "silence",
  "Monopolism",
  "just the blur",
  "dark",
  "Ventilation shafts",
  "hotels",
  "airplanes (any enclosed space where he is easily trapped)",
  "mannequins",
  "splinters",
  "running out of tea",
  "zombies",
  "Closed spaces",
  "public appearance",
  "deadlines",
  "stage fright",
  "math",
  "wide spaces",
  "confined spaces",
  "being still",
  "Bugs (such as spiders)",
  "the color black",
  "and dark areas",
  "insomnia",
  "Winning the lottery?",
];
const goals = [
  "None (glasses without purpose)",
  "Spend all their money to treat their diseases",
  "Artist",
  "Entrepreneur",
  "Writer",
  "raising her son to be happy",
  "wants to travel to Brazil",
  "curing diseases",
  "Defeat his enemies",
  "Marriage",
  "career",
  "children",
  "raising daughter as single parent",
  "Travelling",
  "world domination",
  "Wants to open their own business someday.",
  "raising money for a personal rocket so they can go space",
  "Publishes a book of poems",
  "Become a famous celebrity.",
  "working 9-5 with few breaks.",
  "Tappert spends much of his free time tuning birds in flight. He also devotes a surprising amount of effort to studying human hair structure.",
  "Being a respected ornithologist",
  "being the world's best virtual pourer",
  "to destroy the human world",
  "Becoming head of prosthetics",
  "helping people",
  "traveling",
  "Values justice and mercy above all",
  "writes novels",
  "artist's girlfriend",
  "building up the card tower",
  "killing the human race",
  "enslaving humans",
  "Goalkeeper",
  "becoming an accomplished journalist",
  "to live a quiet life with his partner",
  "no clue! (but is often seen in front of libraries)",
  "be a mechanic",
  "doctor",
  "Wants to be movie director",
  "Be a guide for a living",
  "moving to better place",
  "finding good job",
  "Dealing with annoying situations",
  "getting my life together",
  "personal",
  "educational",
  "self-fulfillment",
  "finish career and get old",
  "being the director of the funhouse mirror museum",
  "Strict fatherly figure.",
  "researching and teaching about cave systems",
  "I want to write and sing about anything and everything in the English language!!!",
  "Write full length novel",
  "Pay off debt",
  "become college educated",
  "wanting to do what makes her happy for a living",
  "stay away from drink",
  "get a real job at a show business",
  "finding a fiancée",
  "rewriting a fantasy book",
  "making the world a better place",
  "Get healthy",
  "finish interiors",
  "meet a man and settle down",
  "personal improvement",
  "Own her own business (accomplished)",
  "writing fashion history dissertation",
  "Remodel the toilet and sink.",
  "Finding someone",
  "turning bookworm",
  "Going to a Gala",
  "finishing degree",
  "start new life in US",
  "studies natural sciences",
  "seeks academic experience",
  "competitive",
  "becomes writer",
  "wants to open a toy store",
  "write masterpiece",
  "write book",
  "studies DNA",
  "spreading knowledge",
  "getting a boyfriend",
  "helps others in difficult situations",
  "easily scared",
  "suffers from illnesses",
  "fragile",
  "vulnerable",
  "useless",
  "fidgety",
  "to make life worth living",
  "becoming a doctor (but",
  "poor at biology)",
  "has a degree in art",
  "anonymous sex",
  "underage sexuality",
  "Repaying parent's debt",
  "Wants to lose 80 lbs",
  "to work for government",
  "Haven't decided",
  "To become a musician",
  "goal is to become a Doctor of medicine",
  "friends",
  "love",
  "find partner",
  "public figure (life goal)",
  "working with animals",
  "Bodybuilder",
  "author",
  "Journalist",
  "World Domination",
  "marrying rich",
  "to build own house",
];
const hobbies = [
  "videogames",
  "reading",
  "movies",
  "anime",
  "sleeping",
  "bird watching",
  "hiking",
  "rockhopping",
  "bouldering",
  "art",
  "street art",
  "Fishing",
  "Traveling",
  "Gardening",
  "Camping",
  "Watching T.V",
  "Reading",
  "computer games",
  "playing video games",
  "gardening",
  "writing",
  "singing",
  "bullettime combat",
  "fishing",
  "mlg",
  "sewing",
  "tinkering with appliances",
  "trying new recipes",
  "aviation",
  "sci-fi",
  "scrapbooking",
  "exercising",
  "sing",
  "dance",
  "work",
  "hip hop",
  "soul",
  "Photography",
  "Gaming",
  "Exercising",
  "Baking",
  "sports",
  "games (especially Dota)",
  "cosplay",
  "gothic poetry",
  "spelunking",
  "aerobics",
  "building clay models",
  "boxing",
  "kites",
  "writing poetry",
  "soccer",
  "Knitting",
  "Drawing comics",
  "cosplaying",
  "conventions",
  "wood carving",
  "learning",
  "fencing",
  "discus throw",
  "archery",
  "javelin throw",
  "skincare",
  "television",
  "traveling",
  "music",
  "kayaking",
  "photography",
  "football",
  "wrestling",
  "running",
  "binge-watching TV",
  "cook",
  "walking",
  "playing videogames",
  "drawing",
  "coding",
  "playing the piano",
  "listening to music",
  "going to the beach",
  "cooking",
  "playing guitar",
  "smoking cigars",
  "doing martial arts",
  "long jogs",
  "classic films",
  "playing games",
  "making sketches",
  "Playing Bass",
  "Sewing",
  "embroidery",
  "Scrolling",
  "Playing games",
  "collects Pokémon cards",
  "studying",
  "video games",
  "Ice cream",
  "ballet",
  "karate",
  "weightlifting",
  "playing chess",
  "researching history",
  "Nail care",
  "gaming",
  "computers",
  "manga",
  "cursing",
  "fitness",
  "yoga",
  "reading books",
  "drinking tea",
  "gambling",
  "drinking",
  "flirting",
  "kite flying",
  "baking",
  "cleaning",
  "telling jokes",
  "star gazing",
  "children",
  "any activity where she is outside and active",
  "sex",
  "fetishes",
  "bdsm",
  "strip poker",
  "dancing",
  "watching sport matches",
  "bicycles",
  "opera",
  "Looking at clouds.",
  "spending afternoons at the beach and swimming.",
  "painting",
  "sculpting",
  "composing",
  "reading poetry",
  "going to concerts",
  "parties",
  "camping",
  "bird-watching",
  "knitting",
  "watching football games",
  "scrapyards",
  "doing art",
  "working out",
  "playing the bass",
  "going to parties",
  "jogging",
  "rock- and jazz-climbing",
  "listens to music",
  "surfs the web",
  "training",
  "swimming",
  "skateboarding",
  "birdwatching",
  "chatting",
  "watching movies",
  "TV",
  "films",
  "heavy metal",
  "classic rock.",
  "playing drums",
  "collecting quarters",
  "collecting nickels",
  "collecting dimes",
  "collecting pennies",
  "collecting coins",
  "counting change",
  "Frequent travel",
  "computer programming",
  "does the cooking",
  "trivia",
  "long walks",
  "gabrielng",
  "skiing",
  "free-climbing",
  "weight lifting",
  "trains",
  "collecting bottle caps",
  "militaria",
  "raising orchids",
  "designing",
  "watching football",
  "watches movies",
  "sings",
  "metal detecting",
  "climbing",
  "snorkeling",
  "to read books",
  "hang out",
  "coffee shops",
  "ramen shops",
  "talking",
  "joking",
];
const likes = [
  "Black Starling",
  "making new friends",
  "RPG games",
  "Camels (animal)",
  "Coffee",
  "Asparagus",
  "tsunga watermelon shakes",
  "shoes",
  "music",
  "make up",
  "Good people",
  "Dog rescue",
  "taking care of stray dogs",
  "swimming",
  "snorkeling",
  "kayaking",
  "campfires",
  "sleeping under the stars",
  "Cats",
  "watching tv",
  "hot dogs",
  "technology",
  "working in garden",
  "wine",
  "croaking frogs",
  "swampy water",
  "swisches",
  "Puppies",
  "flowers",
  "Cute things",
  "vikings",
  "nature",
  "chocolat",
  "Favourite Sport: handbag fighting",
  "spicy noodles",
  "sleep",
  "urban fantasy novels",
  "animals",
  "crab rangoon",
  "big trucks",
  "The name of his team's position",
  "unattractive women",
  "casual sex",
  "exercise",
  "water",
  "astronomy",
  "gardening",
  "(apples)",
  "mathematics",
  "DIY stuffs",
  "tending to flowers",
  "People with different tastes",
  "creatures",
  "friendly mobs",
  "food",
  "clothes",
  "jewelry",
  "movement",
  "space",
  "cold",
  "empty cities",
  "night time",
  "bright light",
  "flames",
  "Safety nets",
  "insurance",
  "union",
  "people criticizing her",
  "Aquariums",
  "Swedish Fish",
  "Crab",
  "low to mid range candy prices",
  "stuffed animals",
  "nerdy shirts",
  "puppies",
  "kittens",
  "leaving things around and forgetting them",
  "Firearms",
  "car",
  "sports",
  "fitness",
  "running",
  "beaches",
  "cats",
  "reading",
  "writing",
  "travelling",
  "animals (snakes",
  "dogs)",
  "gymnastics",
  "theatre",
  "drinks",
  "jokes",
  "games",
  "zine publishing",
  "street fashion",
  "tripe (food)",
  "Italian food",
  "art",
  "coffee",
  "clothing",
  "gossiping",
  "drinking wine",
  "architecture",
  "economics",
  "real estate",
  "social work",
  "Godehard Bohn",
  "Reading",
  "New friends",
  "learning",
  "popular culture",
  "dorodelis",
  "Bubblegum Boy",
  "Calamus oil",
  "nude men",
  "liquor",
  "death metal",
  "smoking",
  "anime",
  "viking metal",
  "I like cooking",
  "especially Thai curries and Indian sweets.",
  "deep fried pickles",
  "lake trout",
  "nuts",
  "fixing motorcycles",
  "Dark",
  "Mystery novels",
  "time travel (fiction)",
  "adrenaline",
  "thrill",
  "alcohol",
  "drug cocain",
  "Receiving – Collection of flowers",
  "astral people who can see me",
  "basketball",
  "tennis",
  "soccer",
  "yoga",
  "weightlifting",
  "volleyball",
  "Pringles",
  "Deep Purple",
  "rock",
  "Censoring objectionable parts (of shows)",
  "hip hop",
  "deep bass",
  "Barbecues",
  "palm trees",
  "programming",
  "Node.js",
  "Firebase",
  "MySQL",
  "Swift",
  "sleeping",
  "singing",
  "dancing",
  "hanging out with friends",
  "Teasing Deandra",
  "history documentaries",
  "vlogging",
  "People doing their jobs",
  "clean",
  "dry",
  "rain",
  "vegetables",
  "outdoors",
  "wind",
  "sun",
  "hot",
  "blue",
  "red",
  "purple",
  "beer",
  "video games",
  "sea animals",
  "cheese pizza",
  "humility",
  "charity",
  "thinking",
  "hair stylists",
  "talking",
  "his coworkers",
  "hangover noodles",
  "Quiche",
  "Likes books (Finance)",
  "television (stock news)",
  "Bodybuilders",
  "Greek Food",
  "Tennis",
  "competence",
  "harmony",
  "sex",
  "walks on beach",
  "fishing",
  "flora",
  "learning new things",
  "iron",
  "crome",
  "steel",
  "fried dumplings",
  "TV",
  "computer games",
  "Loves Animals",
  "old romantic movies",
  "videogames",
  "gym",
  "fantasy stories",
  "spicy food",
  "fish",
  "beef",
  "E-cigarettes",
  "ice cream",
  "morning jogs",
  "salami",
  "electronic devices",
  "repairing locks",
  "going out",
  "hanging out with her friends",
  "Action Games",
  "political debates",
  "parties",
  "Computer Games",
  "loving gestures",
  "Hanging with friends",
  "Animal heads",
  "being single",
  "foxing the law",
  "riches",
  "(Sexually) furries",
  "chubby",
  "tsunderes",
  "big dogs",
  "Playing with a Yo-Yo",
  "lobster thermidor",
];
const personality = [
  "energetic",
  "bold",
  "bossy",
  "loyal",
  "friendly",
  "outgoing",
  "upbeat",
  "enthusiastic",
  "Ambiverted joker",
  "Honest",
  "shy",
  "curious",
  "awkward",
  "motherly",
  "optimistic",
  "knows morse code",
  "loner",
  "snarky",
  "blunt",
  "industrious",
  "dorky",
  "Aloof",
  "authoritarian",
  "arrogant",
  "cruel",
  "sarcastic",
  "gruff",
  "and pompous",
  "a domineering side",
  "short-tempered",
  "rude",
  "headstrong",
  "irresponsible",
  "straight-A student",
  "determined",
  "stubborn",
  "hot headed",
  "sassy",
  "argumentative",
  "persistent",
  "defiant",
  "self-conscious",
  "short temper",
  "adventurous",
  "extroverted",
  "brash",
  "trustworthy",
  "tsundere",
  "cowardly",
  "easily startled",
  "cautious",
  "nihilistic",
  "pessimistic",
  "antisocial",
  "grumpy",
  "confident",
  "reckless",
  "talkative",
  "reliable",
  "forgiving",
  "energetic",
  "fun",
  "flirty",
  "nice",
  "caring",
  "friendly",
  "easygoing",
  "ginger",
  "cheerful",
  "lazy",
  "fat",
  "happy-go-lucky",
  "wannabe",
  "happy",
  "devious",
  "cold",
  "nervous",
  "insecure",
  "introverted",
  "Heroic",
  "Egoistic",
  "Rude",
  "self-hating",
  "clumsy",
  "forgetful",
  "easily frustrated",
  "emotional",
  "outspoken",
  "sociable",
  "distant",
  "hardworking",
  "neat",
  "organized",
  "dangerous",
  "positive",
  "chaotic",
  "wild",
  "bright",
  "happy",
  "passionate",
  "professional",
  "easily angered",
  "strict",
  "timid",
  "easygoing",
  "dandy",
  "calm",
  "campy",
  "spry",
  "rational",
  "loyal",
  "awkward",
  "geek",
  "outgoing",
  "bright",
  "irresistible cuteness",
  "plays tricks",
  "good-hearted",
  "laid-back",
  "respectable",
  "inquisitive",
  "honest",
  "decisive",
  "competitive",
  "ambitious",
  "good sense of humor",
  "a bit gruff",
  "big heart",
  "straight to the point",
  "flustered easily",
  "quiet",
  "serious",
  "easily-annoyed",
  "tomboyish",
  "aggressive",
  "smart",
  "relaxed",
  "playful",
  "Lazy",
  "cynical",
  "straight-edge",
  "Kind",
  "opinionated",
  "flamboyant",
  "benevolent",
  "selfless",
  "calm",
  "elegant",
  "protective",
  "supportive",
  "charismatic",
  "voice of reason",
  "caretaking",
  "helping",
  "overreacting",
  "ambitious",
  "strive for perfection",
  "focused",
  "knows when to let go",
  "confidence",
  "Shy Alpha",
  "blameless",
  "clever",
  "humble",
  "logical",
  "modest",
  "nurturing",
  "temperate",
  "understanding",
  "nice",
  "polite",
  "respectful",
  "wise",
  "collected",
  "sweet",
  "thoughtful",
  "insecure",
  "tom boyish",
  "abrasive",
  "strong-headed",
  "out of touch",
  "strange",
  "cocky",
  "loud",
  "impulsive",
  "angry",
  "nerdy",
  "intelligent",
  "stoic",
  "suave",
  "resourceful",
  "awkward gallantry",
  "funny",
  "agreeable",
  "neurotic",
  "prudish",
  "meek",
  "hyperactive",
  "fearless",
  "powerful",
  "hotheaded",
  "vulgar",
  "sweet",
  "perverted",
  "clean",
  "easy to get along with",
  "kind",
  "tomboy",
  "chaste",
  "narcissistic",
  "goofy artist",
  "helpful",
  "quiet",
  "serious",
  "questionable professional competence",
  "extroverted",
  "introverted",
  "flaky",
  "fussy",
  "impatient",
  "whiny",
  "responsible",
  "sanguine",
  "simple",
  "careful",
  "friendly",
  "Shy",
  "easy-going",
  "cheery",
  "shy padisacha",
  "awkward introvert",
  "taurus",
  "passive",
  "easily swayed",
  "moody",
  "secretive",
  "sly",
  "smug",
  "depressed",
  "easily forgetful",
  "very headstrong",
  "work oriented",
  "stubborn",
  "blunt",
  "heartless",
  "extrovert",
  "pessimeist",
  "loudmouth",
  "choleric",
  "hot-tempered",
  "impetuous",
  "spurns complacency",
  "goal oriented",
  "cheerful",
  "friendly",
  "talkative",
  "witty",
  "tough",
  "creative",
  "Romantic and curious",
  "commanding",
  "jolly",
  "lonely",
  "hard to impress",
  "Arrogant",
  "Annoying",
  "Aggressive",
  "Sarcastic",
  "bashful",
  "defensive",
  "obedient",
  "neglectful",
  "hedonistic",
  "seductive",
  "organised",
  "patient",
  "Prolific",
  "tight-lipped",
  "wary",
  "highly-strung",
  "socially anxious.",
  "Dorky Dumb",
  "Charmer",
  "Indecisive",
  "easily disturbed",
  "slightly racist.",
  "shy introvert",
  "anxious",
  "socially awkward",
  "easily annoyed",
  "irritable",
  "temper",
  "soft",
  "flatass",
  "anxiety",
  "aloof",
  "stressed",
  "workaholic",
  "snob",
  "closed",
  "independent",
  "non-athomebody",
  "cheeky",
  "dominant",
  "critical",
  "realistic",
  "grouchy",
];
const quirks = [
  "stutters a lot",
  "makes bad jokes",
  "hates doing anything.",
  "seduces married guys",
  "always smiling",
  "snorts when laughs hard enough",
  "Partial to bowties",
  "often sass",
  "flips middle finger when mad",
  "taps head when thinking",
  "talks to birds",
  "stims with windchimes",
  "straight",
  "tight lips",
  "always blushes",
  "unibrow",
  "jutting forehead",
  "has long legs",
  "but chubby feet",
  "smiles a lot",
  "has shaky hands",
  "nervous talker",
  "quick decisions",
  "stuttering",
  "being frank",
  "flails arms around when excited",
  "flinches when angry",
  "breaks rules often",
  "likes sweets",
  "has anger issues",
  "not great at keeping secrets",
  "has a criminal history",
  "needs life advice often",
  "flails hands a lot",
  "spouts random facts",
  "fidgeting hands",
  "twiddling thumbs",
  "hates to be called Malinda",
  "dry skin",
  "obsessing over shiny things",
  "high tolerance of spice",
  "straight-laced",
  "obedient",
  "missing index finger",
  "long left leg",
  "talking to kids",
  "climbing",
  "camping",
  "reading",
  "fidgeting",
  "physical exertion",
  "jumping",
  "going for strolls",
  "smoking cigarettes",
  "prostitute",
  "talks funny",
  "tuts loudly",
  "puffy eyes",
  "talks like Donald Trump",
  "has OCD",
  "loves mashed potatoes",
  "Has a walking cane",
  "hates mosquitoes",
  "loves fries",
  "lazy eye",
  "talks with lisp",
  "Snores with open mouth",
  "needs glasses to read.",
  "pushes glasses up nose",
  "speaks fluent english",
  "stutters before every sentence",
  "fiddles with glasses while talking",
  "fidgeting with pens",
  "talking with hands",
  "getting up and pacing around",
  "fidgets nervously",
  "strokes beard",
  "scrambles eggs daily",
  "hates wearing shirts",
  "feminine",
  "snorts when laughs",
  "slouching",
  "doesn't use correct english",
  "chews gum often",
  "smokes tobacco",
  "is an ardent vegan",
  "brushes people off",
  "covers mouth",
  "hates cars",
  "likes to curse",
  "tired deliriousness",
  "messy",
  "talks like (duuude! errybody's got an problems",
  "man! errything'll be fixed up",
  "duuude.)",
  "is a junkie",
  "slut",
  "airhead",
  "snarky",
  "childish",
  "tsundere",
  "chain smoker",
  "likes beavers?",
  "self-mutilator",
  "stutters occasionally",
  "bends down",
  "spreads fingers while holding hands",
  "looks around",
  "absent-minded",
  "awkward",
  "stutters",
  "stammers",
  "stutter",
  "smiles alot",
  "Bites bottom lip when worried or hesitant.",
  "mutters in Albanian",
  "looks down and to the left when lying",
  "smells funky",
  "likes coffee",
  "is polite",
  "determined",
  "close-set eyes",
  "smokes cigars",
  "addicted to candy",
  "heavy sleeper",
  "reads in bathroom",
  "does ballet in living room",
  "lies in hallway and shouts at the television",
  "does makeup in hallway",
  "bathes outdoors",
  "plays game consoles",
  "stays overnight at office",
  "shaves without mirrors",
  "asks about favorite movies and musicians",
  "bad diet",
  "teas refills",
  "is a science geek",
  "likes to use cheesy puns and other dad jokes",
  "likes showing selfies in social media",
  "dresses in traditionally feminine ways",
  "makes morally questionable decisions",
  "uses soft language",
  "drinks coffee regularly",
  "snacks frequently",
  "swings between childlike and professional behavior",
  "flapping arms like a bird",
  "enjoys belching",
  "hog calls",
  "taps fingers",
  "dislikes dogs",
  "addicted to her smartphone",
  "paranoid",
  "sometimes forgets to wear pants",
  "pushes her glasses",
  "lisp",
  "talks to plants",
  "sarcastic at times",
  "Thick accent",
  "eats fruit and vegetables",
  "likes to help others",
  "does things his way",
  "treats everyone like a little child",
  "strict",
  "thinks with his fist (sometimes)",
  "refuses to work during emergencies",
  "likes old movies",
  "sports",
  "and sunbathing",
  "holds cards in right hand",
  "works with left hand",
  "needs glasses to see",
  "talks with a slight Austrian accent",
  "tucks left side of hair behind her ear",
  "habitual hand gestures",
  "air quotes frequently",
  "loves all her fans",
  "likes to flash",
  "bisexual",
  "fancies Arnie",
  "public flasher",
  "exhibitionist",
  "has frequent migraines",
  "avid tea lover",
  "avid video game player",
  "smokes",
  "uses Aussie slang",
  "pushes her glasses up",
  "mutism (rarely speaks)",
  "talking weirdly",
  "moving weirdly",
  "wearing weirdly",
  "d",
  "Doberman dog",
  "yellow",
  "snores",
  "fixes cars",
  "biting nails",
  "eating salad",
  "pushes glasses up her nose",
  "likes people with glasses",
  "hates her ugly face",
  "sucks on lemons",
  "lazy and rude",
  "wacks people with broom",
  "Sociophobe",
  "tucking hair behind left ear when nervous",
  "makes frequent",
  "Australian",
  "jokes",
  "insists on reading captions in Australian accents",
  "absentminded",
  "shy",
  "speaks in russian",
  "snorts when laughing hard",
  "tugs on ears",
  "sometimes gestures with hands when speaking",
  "gets easily distracted by thinking",
  "talks to people via iPad",
  "slouks in chair",
  "twiddles thumbs",
  "blinks",
  "hyacynth will use a separate fork and knife to cut bread before using a napkin to place the bread on.",
  "smoking",
  "talking to himself",
  "bites back inside cheek when concentrating",
  "bites lips",
  "wheezing",
  "fidgeting (taps pen)",
  "chewing gum all the time",
  "fanning self often",
  "pushes glasses up a lot",
  "scar over left eye",
  "chewing gum",
  "being annoying",
  "overly vigorous",
];
const skills = [
  "public speaking",
  "computer programming",
  "fluent in english",
  "french",
  "japanese",
  "loves fishing.",
  "pouring drinks",
  "being handsome",
  "biology",
  "survival skills",
  "sports",
  "computers",
  "singing",
  "piano",
  "cooking",
  "studying",
  "first aid",
  "tourniquet",
  "proficient liar",
  "access to weapons",
  "profanity",
  "street smarts",
  "handicraft",
  "hacking",
  "programming",
  "medical knowledge",
  "cleaning",
  "can use fire magic",
  "3d printing",
  "administration",
  "expertise meteorology",
  "weather patterns",
  "survivalist",
  "palaeontology",
  "hunting",
  "axe combat",
  "can summon skeleton soldiers at will",
  "can summon blacephalons at will",
  "can summon short break at will",
  "can summon angery islanders at will",
  "fluent in three languages",
  "has knowledge in survival skills",
  "has knowledge in firearm skills",
  "good with technology",
  "strong",
  "confident",
  "good cook",
  "knows Morse code",
  "can fence",
  "writes wit",
  "fluent in elephant",
  "can read body language",
  "Immune to fire",
  "shapeshift",
  "float",
  "scream very loud",
  "Losing at chess",
  "fixing computers",
  "fixing plumbing",
  "plumbing",
  "CPR",
  "EMS (Emergency Medical Services)",
  "handcuffing",
  "knot tying",
  "splinting",
  "medical treatments",
  "Skilled driver",
  "able with firearms",
  "stamina to run for miles",
  "skilled chef",
  "swimming ability",
  "Carpentry",
  "event planning",
  "clothes shopping",
  "training mammals",
  "running",
  "wrestling",
  "immobilizing limbs",
  "Marksmanship",
  "uses German language",
  "organization",
  "immunity to fire",
  "summon",
  "fighting",
  "swimming",
  "pole dancing",
  "pyrokinesis",
  "urban survival",
  "memorizing",
  "concentrating",
  "gambling",
  "Can wallpaper anything",
  "artistic",
  "crafty",
  "physical resistance",
  "worries a lot",
  "fucking hot",
  "handling dead bodies",
  "foreign languages",
  "embalming",
  "defusing conflicts",
  "knows anatomy",
  "fashion design",
  "wields large scythe",
  "machinery",
  "Proficient at math",
  "some martial arts",
  "knows history",
  "speaking in third-person",
  "driving",
  "memory for faces and names",
  "fixes equipment",
  "computer hacking",
  "robotics",
  "marksmanship",
  "martial artist",
  "skilled musician",
  "proficiency with various weapons",
  "good fighter",
  "using tablet",
  "wearing headphones",
  "calm",
  "metalhead",
  "good at wood carving",
  "fixes things",
  "fencing",
  "melee weapon defense",
  "firearm handling",
  "art",
  "calculating numbers",
  "writes in ledger",
  "memory",
  "strategy",
  "geography",
  "cooks",
  "paints",
  "plays guitar",
  "stalking",
  "lying",
  "kick-boxing",
  "weapons",
  "riding",
  "sarcasm",
  "et cetera",
  "martial arts",
  "fitness",
  "climbing",
  "skateboarding",
  "invention",
  "engineering",
  "physical health",
  "boomerangs",
  "reads minds",
  "none",
  "ice sculpting",
  "self-hypnotism",
  "amnesia-causing accident",
  "beer",
  "technology",
  "digs",
  "unarmed fighting",
  "firearms training",
  "intimidation",
  "Carrying things",
  "ice skating",
  "athletics",
  "rock climbing",
  "tech support",
  "sailing skills",
  "weapon use",
  "hand to hand combat",
  "Can play trumpet and piano",
  "fixing engines",
  "C++ programming",
  "Machine language",
  "High-Performance Computing",
  "Programming",
  "Teaching",
  "writing",
  "math",
];

function getMore() {
  const amount = Math.floor(Math.random() * 3) + 1;
  const attributes = {
    dislikes: "",
    goals: "",
    hobbies: "",
    likes: "",
    personality: "",
    quirks: "",
    skills: "",
  };
  for (let i = 0; i < amount; i++) {
    attributes.dislikes +=
      dislikes[Math.floor(Math.random() * dislikes.length)] + ", ";
    attributes.goals += goals[Math.floor(Math.random() * goals.length)] + ", ";
    attributes.hobbies +=
      hobbies[Math.floor(Math.random() * hobbies.length)] + ", ";
    attributes.likes += likes[Math.floor(Math.random() * likes.length)] + ", ";
    attributes.personality +=
      personality[Math.floor(Math.random() * personality.length)] + ", ";
    attributes.quirks +=
      quirks[Math.floor(Math.random() * quirks.length)] + ", ";
    attributes.skills +=
      skills[Math.floor(Math.random() * skills.length)] + ", ";
  }
  attributes.dislikes = attributes.dislikes.slice(0, -2);
  attributes.goals = attributes.goals.slice(0, -2);
  attributes.hobbies = attributes.hobbies.slice(0, -2);
  attributes.likes = attributes.likes.slice(0, -2);
  attributes.personality = attributes.personality.slice(0, -2);
  attributes.quirks = attributes.quirks.slice(0, -2);
  attributes.skills = attributes.skills.slice(0, -2);

  return attributes;
}
export default getMore;
